### ISSUE TITLE
The "ResolveNativeReferences" task failed unexpectedly

### ISSUE THREAD

**Issue by Sergtek** [drasticactions/Drastic.IQKeyboardManager#1]
<img width="398" alt="error1" src="https://user-images.githubusercontent.com/20904914/220621890-17ec742c-af17-4835-a654-83494537c86d.png">

I am interested in using this nuget in my project but I am getting the following compile error after installing the nuget: "The "ResolveNativeReferences" task failed unexpectedly".

**Nuget version:**

- Drastic.IQKeyboardManager 1.0.0

<img width="502" alt="error2" src="https://user-images.githubusercontent.com/20904914/220621894-89e66da1-c3de-4ac9-be94-511c3c593f11.png">
As you can see in the .csproj image, the only difference from your sample project is that I have more platforms in the TargetFrameworks tag and the nuget is installed with the condition:  Condition="'$(TargetFramework)' == 'net7 .0-ios'" to avoid problems with other platforms, can you think of what might be happening? I leave an example project on GitHub:

[https://github.com/nacompllo/IQKeyboardManagerIssue/tree/master/IQKeyboardManagerIssue
](https://github.com/nacompllo/IQKeyboardManagerIssue/tree/master/IQKeyboardManagerIssue
)

**Comment by drasticactions** [comment]
I believe you're hitting this issue, https://github.com/xamarin/xamarin-macios/issues/16001, specifically https://github.com/xamarin/xamarin-macios/issues/16001#issuecomment-1398175706. I'm packaging this as an xcframework and the SDK/Platform on Windows is not able to extract it.

I could change it to just reference the framework, but then I would need to bundle both device and simulator frameworks and I'm not sure how to do that, nor do I really feel like it. I rather the original issue be fixed by the SDK/Platform team rather than me hack around it. Sorry!
